language: node_js
node_js:
- 'node'
after_success:
- npm run coveralls
- npm run lint
branches:
  only:
  - master
deploy:
  on:
    branch: master
  provider: npm
  skip_cleanup: true
  email: manthanhd@live.com
